language: cpp

compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes ppa:canonical-qt5-edgers/qt5-beta-proper
  - sudo apt-get update
  - sudo apt-get install qt5-qmake qtbase5-dev libqt5sql5-sqlite libqt5sql5 qt5-default

script:
  - mkdir $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR/build
  - qmake -qt=qt5 $TRAVIS_BUILD_DIR/DS2PlusPlus/DS2PlusPlus.pro
  - make
